version: "3.9"
services:
  db:
    image: postgres:16
    container_name: marshanta_db
    environment:
      POSTGRES_DB: marshanta
      POSTGRES_USER: marshanta
      POSTGRES_PASSWORD: marshanta
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U marshanta -d marshanta"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data:
