name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies (workspaces)
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: API smoke test
        env:
          NODE_ENV: test
        run: node apps/api/scripts/smoke.js

      - name: Web smoke test
        run: npm --workspace apps/web run smoke
